name: Deploy to ACSWeb

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - uses: actions/checkout@v2
    
    # Setup node (used to download the React app's dependencies and to build the app)
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    
    # Install the React app's dependencies
    - run: npm install
    
    # Build the React app itself
    - run: npm run build
    
    # Deploy the compiled result to the ACSWeb account
    - uses: asg017/actions/acsweb@master
      with:
        username: tritonthenix
        password: ${{ secrets.ACSWEB_PASSWORD }}
        local_dir: "./build/"
