name: Deploy to ACSWeb using GitHub Actions

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: self-hosted  # Specify self-hosted here

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js and build React app
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Build React app
      run: npm run build

    - name: Deploy using SCP with password
      run: |
        scp -r ./build/* tritonthenix@acsweb.ucsd.edu:public_html/
      env:
        SSH_PASS: ${{ secrets.ACSWEB_PASSWORD }}

    - name: Clean up
      run: |
        Remove-Item -Path ./build -Recurse -Force
